# Generated by Django 2.1.7 on 2019-05-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20190306_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='category',
            field=models.CharField(choices=[('NEWS', 'News'), ('ANDROID', 'Android'), ('COMPUTER', 'Computer'), ('OTHERS', 'Others')], default='OTHERS', max_length=20),
        ),
        migrations.AlterField(
            model_name='home',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
