# Generated by Django 2.1.7 on 2019-05-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190518_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='category',
            field=models.CharField(choices=[('NEWS', 'News'), ('ANDROID', 'Android'), ('COMPUTER', 'Computer'), ('OTHERS', 'Others')], default='OTHERS', max_length=20),
        ),
    ]
