# Generated by Django 2.2.2 on 2019-06-19 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20190518_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
